### ISSUE TITLE
Problems with .close-panel

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#1000]
.close-panel doesn't work under all circumstances.

1. After an injection within a modal, any .close-panel that is injected is not picked up by pat-modal and won't function as expected. This used to work in the past.
2. When a modal is opened by a link on a tooltip an that link on the tooltip has .close-panel on it, then it may occur that the modal doesn't open. This seems to be dependent on how speedy the server reacts. 
3. It's not possible to close a modal from a modal in order to open a new modal. 

Talked about these issues with @thet last Monday and he indicated that this might be solvable by putting all the functionality of .close-panel in an independent script.

**Comment by pilz** [comment]
The branch in oira.prototype is [modal-modal](https://github.com/syslabcom/oira.prototype/tree/modal-modal)

Next step: Hannes and Cornelis to do a call where the changes are discussed and approved or amended.

**Comment by pilz** [comment]
Call to be done today at 13:00

**Comment by thet** [comment]
@cornae please see if the problem is fixed in curent [oira.prototype ()](https://github.com/syslabcom/oira.prototype) and eventually close this ticket.
