### ISSUE TITLE
Pattern Video player

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#106]
A video player than can be instantiated by simply including a video tag in the markup:

```
<video src="some-video.m4v" class="pat-video" data-pat-video="controls: autoplay play-pause timeline">
  Content that will be replaced. E.G. a transcript of the video content for visually impaired. 
</video>
```

If a YouTube URL is entered, it will play the YouTube in a chromeless player. 

Suggestion: JW Player is a great player. Though not open source. User will get a watermark until he buys a license, which seems fine to me for now. I don't know of any open source players that have all the functionality that JW player has in terms of skinning, transparent HTML5/Flash usage, excellent cross browser support.

**Comment by pilz** [comment]
Question: We have a design for a video content type in proto already. Without dedicated player. Is it correct that we have waited long enough and should just rely on HTML5 Video now? Then we could close this and move it to development.

**Comment by cornae** [comment]
I would say yes. A file format check needs to be there through on the file upload of the video object and if you upload a file directly to the sidebar, then the backend has to decide whether to turn it into file object or a video object, depending on the format.
