### ISSUE TITLE
Clarify issues around latest release

### ISSUE THREAD

**Issue by pilz** [Patternslib/Patterns#1192]
### 1) Reported: Support submit buttons with formaction in forms without an action attribute.

Also fixed within this request:

- For submit buttons with a formaction, do not call ajax.onClickSubmit twice.
- Support submit buttons without a type attribute.

This fix involved a number of changes in pat-inject and pat-ajax.

PR: [#1175](https://github.com/Patternslib/Patterns/pull/1175) (merged: 2023-08-11)
Related release: [9.9.6-alpha.0](https://github.com/Patternslib/Patterns/releases/tag/9.9.6-alpha.0) (released: 2023-08-11)

### 2) Fix for "unwanted scrolling when inside collapsible"

PR: [#1176](https://github.com/Patternslib/Patterns/pull/1176) (merged: 2023-08-30)
Scrum ticket: [scrum-1455](https://github.com/syslabcom/scrum/issues/1455)
Proto ticket: [proto-166](https://github.com/syslabcom/quaive.prototype/issues/166)
Related release: [9.9.6-alpha.1](https://github.com/Patternslib/Patterns/releases/tag/9.9.6-alpha.1) (merged: 2023-08-30)

### 3) Fix performance problems with pat-checklist

This PR doesn't touch pat-inject but it introduces some fixes and features for the `remove_event_listener` method.
This should be unrelated to any problems which came afterwards.

XXX Demo: https://patternslib.com/demos/checklist
PR: [#1180](https://github.com/Patternslib/Patterns/pull/1180) (merged: 2023-10-16)
Scrum ticket: [scrum-1647](https://github.com/syslabcom/scrum/issues/1647)
Proto ticket: [proto-190](https://github.com/syslabcom/quaive.prototype/issues/190)
Related release: [9.9.6-alpha.3](https://github.com/Patternslib/Patterns/releases/tag/9.9.6-alpha.3) (released: 2023-10-16) and 9.9.6 final (released: 2023-10-20).

### 4) Fix for forms with invalid data submitted even with pat-validation.

This fix introduces a number of changes in pat-inject, mainly waiting for a tick before initializing pat-inject and some changes in the inject initialization for forms.

This PR is most likely the cause for upcoming problems.

PR: [#1179](https://github.com/Patternslib/Patterns/pull/1179) (merged: 2023-10-16)
Proto ticket: [proto-167](https://github.com/syslabcom/quaive.prototype/issues/167)
Related release: [9.9.6-alpha.3](https://github.com/Patternslib/Patterns/releases/tag/9.9.6-alpha.3) (released: 2023-10-16) and 9.9.6 final (released: 2023-10-20).

### 5) Fix problem with pat-autosubmit.

This fixes a problem where pat-inject and pat-autosubmit didn't work together anymore.

This fixes a regression introduced in the Patternslib 9.9.6 release.

PR 1: [#1183](https://github.com/Patternslib/Patterns/pull/1183) (merged: 2023-10-22)
PR 2: [#1184](https://github.com/Patternslib/Patterns/pull/1184) (merged: 2023-10-23)
Related release: [9.9.7](https://github.com/Patternslib/Patterns/releases/tag/9.9.7) (release: 2023-10-23)

### 6) Fix pat-subform and pat-push not working with pat-inject.

This fixes a regression introduced in the Patternslib 9.9.6 release.

PR: [#1185](https://github.com/Patternslib/Patterns/pull/1185) (merged: 2023-10-23)
Related release: [9.9.8](https://github.com/Patternslib/Patterns/releases/tag/9.9.8) (release: 2023-10-23)

### 7) Fix issue with submit buttons which are added later. 

When a form was initialized with pat-inject and some form elements / submit buttons were added later (e.g. via another pat-inject call, probably via pat-autosubmit), those buttons were not initialized.

This fixes a regression introduced in the Patternslib 9.9.6 release.

XXX Demo: []()
PR: [#1186](https://github.com/Patternslib/Patterns/pull/1186) (merged: 2023-11-03)
Related release: [9.9.9](https://github.com/Patternslib/Patterns/releases/tag/9.9.9) (released: 2023-11-06)

### 9) Fix a problem with incorrect data with pat-autosubmit.

Fix a problem where pat-autosubmit did not correctly send the submitting button's value.

This fixes a regression introduced in the Patternslib 9.9.6 release.

This also fixes a typo slipped in 9.9.7 which caused pat-autosubmit not to work with pat-subform anymore.
 
This fixes a regression introduced in the Patternslib 9.9.7 release.

PR: [#1189](https://github.com/Patternslib/Patterns/pull/1189) (merged: 2023-11-08)
Related release: [9.9.10-alpha.0](https://github.com/Patternslib/Patterns/releases/tag/9.9.10-alpha.0) (released: 2023-11-08)

### 10) Fix auto submit on non-form elements.

Fix a problem introduces in Patternslib 9.9.7 where pat-autosubmit did not work when not defined on a form or input element.

This fixes a regression introduced in the Patternslib 9.9.7 release.

PR: [#1190](https://github.com/Patternslib/Patterns/pull/1190) (merged: 2023-11-10)
Releated release: [9.9.10-alpha.1](https://github.com/Patternslib/Patterns/releases/tag/9.9.10-alpha.1) (released: 2023-11-10)

### 12) Fix again lost support for pat-subform.

Subform was recently lost when introducing dom.find_form.
Now subform support is back in pat-autosubmit.

This fixes a regression introduced in the Patternslib 9.9.10-alpha.1 release.

PR: [#1193](https://github.com/Patternslib/Patterns/pull/1193) (merged: 2023-11-17)
Releated release: [9.9.10-alpha.3](https://github.com/Patternslib/Patterns/releases/tag/9.9.10-alpha.3) (released: 2023-11-17)

### 8) Add feature to support submit buttons with child elements.

This adds support for submit buttons with child elements (e.g. a span within a button). Before, when clicking on a span within a button would not result in a pat-inject submit. Now it does. This is a new feature.

PR: [#1187](https://github.com/Patternslib/Patterns/pull/1187) (merged: 2023-11-04)
Related release: [9.9.9](https://github.com/Patternslib/Patterns/releases/tag/9.9.9) (released: 2023-11-06)

### 11) Improve the code to find the related form for an input.

This is just a very minor code optimization which I overlooked in the previous release without any effect on functionality.

PR: [#1191](https://github.com/Patternslib/Patterns/pull/1191) (merged: 2023-11-10)
Releated release: [9.9.10-alpha.2](https://github.com/Patternslib/Patterns/releases/tag/9.9.10-alpha.2) (released: 2023-11-10)

### Quaive: CTRL-A behaves erratically and Quaive: Table hopping

1) Select-all in tables don't work. The fix involved adding another dom element after the table. For details see the PR.
2) Moving the mouse over a table in tiptap would make the table hop.

Scrum ticket 1: [scrum-1604](https://github.com/syslabcom/scrum/issues/1603)
Scrum ticket 2: [scrum-1604](https://github.com/syslabcom/scrum/issues/1604)
PR: [#61](https://github.com/Patternslib/pat-tiptap/pull/61) (merged: 2023-10-16)
Released pat-tiptap: [4.8.6](https://github.com/Patternslib/pat-tiptap/releases/tag/4.8.6) (released: 2023-10-16)
Released Patternslib: [9.9.6-alpha.3](https://github.com/Patternslib/Patterns/releases/tag/9.9.6-alpha.3) (released: 2023-10-16) and 9.9.6 final (released: 2023-10-20).

### fix: Allow to select-all in tables.

A follow-up fix for [#61](https://github.com/Patternslib/pat-tiptap/pull/61).

Scrum ticket: [scrum-1604](https://github.com/syslabcom/scrum/issues/1603)
PR: [#64](https://github.com/Patternslib/pat-tiptap/pull/64)
Not yet released, was only provided in a branch to Daniël. Needs a proper release.

**Comment by thet** [comment]
@cornae yes, that is included with pat-tiptap 4.9.0, which is part of Patternslib 9.9.10.

Heads up: it's not called tableWrapper but `scroll-table`, like discussed.
