### ISSUE TITLE
Markdown header level shift

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#216]
When you inject markdown as HTML into a page that has already an H1, H2 or different, you'll need to start the Markdown you're writing with three hash headers. On a markdown level it's not nice, as I prefer the markdown to have no knowledge of where it will end up. Also I don't like it that if I reuse a content snippet in multiple place, I'm forced to use the same header hierarchy across these pages. 
## Suggested solution: HTML5

Fork the Markdown parser and add an HTML5 output mode. HTML5 recommends to use nested sections, each with an H1, instead of using H1 through H6. In CSS I could style `section h1`, `section section h1`, instead of `h1`, `h2`, etc. 

The mode could be triggered by: `output: HTML5` as opposed to `output: XHTML`, which should probably remain the default. 

The advantages are that the target HTML structure is source structure agnostic and vice versa. 
## Alternate solution: Header level property

A header level property would provide the possibility to 'shift' the header levels in the HTML output. For instance `h-level: -1` would shift every H1 to an H2, every H2 to an H3, etc.

The disadvantage of this solution is that while the source needs no knowledge of the target, the target still needs knowledge of the source. For this reason I strongly prefer the first solution.

**Comment by jcbrand** [comment]
I've replaced the forked copy of Pagedown with a bower managed version of [showdown](https://github.com/showdownjs/showdown).

The old hooks which @wichert used to implement this fix aren't available any more which means that this issue needs to now be solved anew.

The solution it seems to write an extension for showdown: https://github.com/showdownjs/showdown#creating-markdown-extensions

Reopening and assigning to myself.
