### ISSUE TITLE
Figure out how to expose development documentation

### ISSUE THREAD

**Issue by wichert** [Patternslib/Patterns#254]
We have various bits of developer documentation:

* How to write a new pattern.
* Various bits of internal API documentation.
* Technical description of exact parser syntax.
* How to run tests.
* How to integrate in applications.

Currently we have no place for these in the website, so they are only kept as text files in the source. It would be nice to have them available via the website as well.

**Comment by jcbrand** [comment]
We've reorganized the documentation and it's now shown in Patterns-site but exist in Patterns repo.

This is explained in the Patterns-site [README](https://github.com/Patternslib/Patterns-site/tree/master#how-to-include-the-demos-and-docs-for-the-individual-patterns).
