### ISSUE TITLE
pat-sortable inside pat-modal

### ISSUE THREAD

**Issue by reinhardt** [Patternslib/Patterns#329]
When pat-sortable is used inside a pat-modal and the current URL does not have a trailing slash, then dragging causes the modal to close and the page to reload with '/#' appended to the URL.

Example: https://dev.star.syslab.com/stardesk/workspaces/syslab.com
Gearbox ("Settings") - "Change custom order of tags"

Happens in Firefox (tested with 22.0 on Ubuntu)

**Comment by jcbrand** [comment]
@reinhardt: I'm assuming this was fixed, closing this ticket.
