### ISSUE TITLE
Bug in Patternslib Modal Panel Firefox

### ISSUE THREAD

**Issue by MarinusW** [Patternslib/Patterns#353]
Resizing the demo page http://patternslib.com/demo/modal/index.html) (with modal panel opened) causes repeated cloning of the modal panel, see screenshot of FF’s inspector. After a few seconds of resizing, the browser is flooded with thousands of panel clones which causes the browser to stop responding.
 
In Chrome a few clones are created, but they are immediately cleaned up, so the browser keeps responding.

![image](https://f.cloud.github.com/assets/5765684/1732152/4a60554a-6318-11e3-8a38-4523dd95affc.png)

**Comment by jcbrand** [comment]
Tested and doesn't seem to be an issue any more.
