### ISSUE TITLE
the custom require.config in the patterns lib  doesn't reference the correct names

### ISSUE THREAD

**Issue by frontendplace** [Patternslib/Patterns#365]
When I change the paths in the main-no-bundle.js  to :
        'pat-logger': '../src/core/logger',
        'pat-parser': '../src/core/parser',
        'pat-utils': '../src/core/utils',
        'pat-compat': '../src/core/compat',
        'pat-jquery-ext': '../src/core/jquery-ext',
        'pat-registry': '../src/core/registry',
        'pat-ajax': '../src/pat/ajax', 
it works again

**Comment by jcbrand** [comment]
That file has in the meantime been removed.
