### ISSUE TITLE
Checked class not set on checklist

### ISSUE THREAD

**Issue by aoudijk** [Patternslib/Patterns#381]
A checked attribute is set on the second item in the checklist. What goes wrong is:

- Class 'checked' is not initially set
- Class 'checked' only appears on the second label if the first items has been selected at least once
- Class 'checked' is never set on the input, only on the label (not the core of this issue)

The problem does not seem to occur if the first item in the list is initially selected. Test case: http://f343rn9a.informaat.com/test.html

Oddly, with the exact same HTML code and the same .js package, the problem does not seem to occur at:

http://jsfiddle.net/#&togetherjs=a7h0ctMxb4

Where is the error? Anything we're overlooking?

**Comment by fulv** [comment]
@cornae I've uploaded your example with the current patterns bundle here:
http://patternslib.s3-website.eu-central-1.amazonaws.com/

**Comment by jcbrand** [comment]
This is fixed, right? Closing...

**Comment by cornae** [comment]
Yes, In the example it looked fixed. It can only be tested in within the project once Patterns 2.x is rolled out on the patterns website, as this project has no knowledge on board to build their own bundles.

**Comment by jcbrand** [comment]
@cornae is there an estimate date or roadmap for this?

**Comment by cornae** [comment]
No. It’s also actually not prioritised or on the backlog of PI, where it should probably be, since so many things start to depend on it more and more. Where amongst documentation and new demo pages.

**Comment by fulv** [comment]
@cornae do we need to create a new issue for building the Patterns 2.x bundle on our own?

**Comment by cornae** [comment]
Probably a new ticket for finishing the new site that is a prerequisite for all the 2.x stuff to happen.

**Comment by jcbrand** [comment]
@fulv: I'm not sure what you mean. Whenever you run "make bundle" in ploneintranet.theme you're building a Patterns 2.x bundle.
