### ISSUE TITLE
Create a pat-masonry based on pat-packery

### ISSUE THREAD

**Issue by pilz** [Patternslib/Patterns#384]
http://masonry.desandro.com
http://packery.metafizzy.co

Masonry has an advantage for dynamically resizing designs (@cornae correct me) and is MIT licensed.
Both are very similar, so there is hope that we can mainly exchange the underlying js lib and keep most of the existing pat-packery code, calling it pat-masonry - and including it into patterns core.

**Comment by jcbrand** [comment]
Hi @cornae I've now moved pat-masonry to Patterns core. I think you'll want to fix the CSS and markup of the pattern's documentation. 

https://github.com/Patternslib/Patterns/tree/master/demo/masonry
