### ISSUE TITLE
Extension for injection/modal

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#389]
A regular form has an action attribute, pointing at the desired feedback page that the user gets to see when the submit button is hit. There are also cases in which a form will have multiple submit buttons, each expecting a different feedback page. For instance in case of a wizard that has a decision tree behind it. For these cases the 'formaction' attribute is used on the submit button itself. The value of the formaction attribute overrides the value of the action attribute on the form, but only for that respective submit button. This works in all modern browsers and in IE 10+ without additional JavaScript. 

Pat-inject and pat-modal currently don't seem to respect the formaction attribute. What I currently need is that the injection script also looks if there's a formaction attribute and respect its value. The initial need is limited to a situation with 'pat-modal' on a form. I can however foresee the need for formations in combination with pat-inject too in the near future. 

![fullsizerender](https://cloud.githubusercontent.com/assets/738601/5557133/8c3df9cc-8cf2-11e4-8bad-159a1d3aaf7d.jpg)

I vaguely remember that formactions have been discussed in the passed between @wichert, @chaoflow and myself, but I can't remember if there was any complication with it.

**Comment by fulv** [comment]
@jcbrand: it was mentioned today that you might already have something implemented for Staralliance.  Could you please let me know the status?  I'd like to work on this.

**Comment by jcbrand** [comment]
@fulv whatever I did, was done in Patterns core. I did work to allow pat-subform to submit a form based on a *formaction* button being clicked.

I think if you grep for *formaction* and also look at the commits from 2 to 3 weeks ago you'll see what I did.

**Comment by jcbrand** [comment]
@fulv any update on this? If not, I'd like to take this one for next week's sprint.

**Comment by fulv** [comment]
I've been looking at pat-inject yesterday, and might have something to show
today.

**Comment by fulv** [comment]
@jcbrand, please take a look at my branch https://github.com/Patternslib/Patterns/tree/inject-with-formaction and let me know what you think.  I will work more on it tomorrow.

This is my first attempt at handling `formaction` attributes.  The main thing that I know is missing is handling anchors in the `formaction`.  E.g.: when `formaction` is:

    formaction="/feedback/banner-notifications#documents-cut"

then the source `selector` for all configs should be replaced by `#documents-cut`.
