### ISSUE TITLE
CSS3 support for Bumper pattern

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#392]
Bumper would place a dynamic class `sticky-supported` on the bumpered item, when the browser supports 'position: sticky', which takes over half of the bumper functionality. Currently Safari supports this and it performs much better with 'position: sticky' than with JavaScript driven positioning.

**Comment by fulv** [comment]
(Apparently, it's supported by all recent versions of Firefox, as well: http://caniuse.com/#feat=css-sticky.)

**Comment by fulv** [comment]
Are you suggesting some kind of browser sniffing to determine support for `sticky`, and setting the class `sticky-supported` based on that?
If so, is there a precedent in Patternslib for conditional behavior based on browser capability, to your knowledge?

**Comment by cornae** [comment]
Kind of. More feature sniffing. Maybe its the case that you can use the Api of modernizr for it. It should already detect if the browser supports this feature but doesn't put a class itself.
