### ISSUE TITLE
Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by Kotrotsos** [Patternslib/Patterns#409]
Goodmorning

When using the example code to create a 'new pattern' I am running into two problems, one of which I can fix, the other I can't trace back so easy.

The first one is that we are missing a comma in de definitions
```
 "pat-registry",
 "pat-parser" << comma was missing here
 "pat-base"
```

The other is that I am getting a 

``` Uncaught TypeError: Cannot read property 'extend' of undefined ```

On 

```
return Base.extend({
        name: "colorchanger",
```

Base seems to be undefined. I am using the example code for the colorchanger from the website as is. 

Thank you.

**Comment by jcbrand** [comment]
`Base` is supposed to come from `pat-base`, which needs to be configured via `require.config` (see main.js) to point to src/core/base.js.

I hope you're using require.js. Support for a non-require.js usecase is spotty.

**Comment by Kotrotsos** [comment]
I'm using Almond, so the bundle.js that is provided. And I am following the instructions to create a new pattern. But I think I am missing some parts there.

**Comment by Kotrotsos** [comment]
So what I am having is

```
bundle.js         << see gist.
pat-colorchanger.js
index.html
```
And I reference them in order.
I use the pattern as:

```
<p class="pat-colorchanger" data-pat-colorchanger="color: blue" style="color: red">
	    This text will turn from red into blue after 3 seconds.
</p>
```

Bundle.js contains:
https://gist.github.com/Kotrotsos/99b4f553a1b44cecb575

**Comment by jcbrand** [comment]
Ok, I see now what you're trying to do.

As a ~~hack~~^^fix, make the same change that I just did here:  https://github.com/Patternslib/Patterns/commit/6c6cc68238325047266dd86c7442d2f98bee14b7

Put that line in the same place at the end of your bundle.js file, and I think it should then work.

**Comment by Kotrotsos** [comment]
Thank you very much. It works now but with a couple of changes to the example code. Namely:

```
 var parser = new Parser("colorchanger"); // changed this from 'example'
    //parser.add_argument("color", "green"); // A configuration parameter and its default value.
    parser.addArgument("color", "green");
```

Thank you again

**Comment by jcbrand** [comment]
You're welcome. Thanks for the feedback, I've updated the doc with your changes.
