### ISSUE TITLE
pat-auto-scale container size

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#430]
Auto scale offers two method to scale: `method: content` and `method: scale`. With `scale` the original footprint of the element is maintained. So if the element is scaled up, it might overlap surrounding elements. With the option `content`, the surrounding content is pushed away away if the element grows. 

The problem with the content option is that Firefox still doesn't support the CSS property `zoom: `, which is used for the content scale method and is probably also not going to support it in the future. Because of this, this method cannot be used in situation where Besides Safari, Chrome, IE 5.5+, Opera and other browsers also FireFox has to be supported and this scaling method is desired.

The solution could be simple:

1. Measure the original footprint of the element that has `class="pat-auto-scale"` on it
2. Perform the regular scaling
3.  Inject an element `<div class="auto-scale-wrapper">` around the element that has `class="pat-auto-scale"` on it. Apply inline styles for width and height on this element with values that match the original footprint values multiplied with the scaling factor.

With the right CSS styling, the scaling will work identical in all browsers. Making even `method: content` obsolete.

**Comment by pilz** [comment]
Implemented in patterns master. @cornae have a look. If you do a make fetchrelease in the PI proto, you should be able to test.

**Comment by cornae** [comment]
Beautiful! So this is available now also for other Patterns projects?

Op zo 31 jan. 2016 om 17:41 schreef Alexander Pilz <notifications@github.com

**Comment by pilz** [comment]
Yes, you just need to use the most recent patternslib version
> Am 04.02.2016 um 22:59 schrieb Cornelis G. A. Kolbach <notifications@github.com>:
> 
> Beautiful! So this is available now also for other Patterns projects?
> 
> Op zo 31 jan. 2016 om 17:41 schreef Alexander Pilz <notifications@github.com
> >:
> 
> > Implemented in patterns master. @cornae <https://github.com/cornae> have
> > a look. If you do a make fetchrelease in the PI proto, you should be able
> > to test.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Patternslib/Patterns/issues/430#issuecomment-177546102>
> > .
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/Patternslib/Patterns/issues/430#issuecomment-180069998>.
> 


Alexander Pilz

--
SYSLAB.COM GmbH, Landwehrstraße 60-62, 80336 Munich, Germany, Amtsgericht Muenchen, HRB 135057, Gabriele Loher, Alexander Pilz

**Comment by cornae** [comment]
Yep. Great! But it might be worth into this duplication wrapper div issue.

Op do 4 feb. 2016 om 23:03 schreef Alexander Pilz <notifications@github.com
