### ISSUE TITLE
Reducing rendered HTML by different option acquisition strategy?

### ISSUE THREAD

**Issue by thet** [Patternslib/Patterns#434]
Pattern configuration can get quite verbose, for example for TinyMCE in Plone (really, really huge configuration) or when a set of elements get all similar configuration, like with pat-contentloader/pat-inject. I'd like to find a way to reduce the HTML output size.

I see three possible options, but I'm not sure about the complexity involved and unwanted side effects. But I'd like to hear your opinions.

While writing this, I think option 3 works best for me at the moment and is least costly.

### 1) Acquire options from parent elements.

For example, this Mockup's ``pat-contentloader`` for one element on Plone's batchnavigation:

```
<nav id="main_pagination" class="pagination">
<ul>
  <li>
    <a href="http://URL/TO/COLLECTION/?b_start=40" class="pat-contentloader" data-pat-contentloader='{"url": "http://URL/TO/COLLECTION/?b_start=40&ajax_load=1", "target": "#content"}'>3</a>
    </li>
    ...
  </ul>
</nav>
```

With option acquisition from parent elements it would could look like:
```
<nav id="main_pagination" class="pagination pat-contentloader" data-pat-contentloader='{"base_url": "http://URL/TO/COLLECTION/?ajax_load=1", "target": "#content"}'>
<ul>
  <li>
    <a href="http://URL/TO/COLLECTION/?b_start=40" class="pat-contentloader" data-pat-contentloader='{"url_part": "&b_start=40"}'>3</a>
    </li>
    ...
  </ul>
</nav>
```

But acquisition must stop at some point, otherwise the pattern could get misconfigured, if the same pattern is somewhere defined in the direct hierachy.

### 2) Getting Base configuration from JSON

Base config could be stored in a JSON file. If a set options should only applied to a specific DOM node, we would need a id for that. E.g.

```
{
    "pat-contentloader": {
        "target": "#content",
        "_specific_nodes": [
            {
                "selector": "#main_pagination",
                "options": {
                    "base_url": "http://URL/TO/COLLECTION/?ajax_load=1"
                 }
            }
        ]
    }
}
```
Something like that.

### 3) Just implement option acquisition in Pattern itself.

To solve my specific use case, where I don't want to repeat similar configuration options for the pagination elements where I want to use ``pat-contentloader``, I could implement that just in ``pat-contentloader`` itself. I would apply ``pat-contentloader`` on ``<nav>`` and add an option to select the source nodes ``"source_nodes": "a"`` and configure the individual options on those nodes via another data-pat-contentloader attributes.

**Comment by jcbrand** [comment]
#1 is already the case in patterns. A specific pattern will look for parent patterns of the same type and inherit their config. So they "cascade" similar to CSS.

**Comment by thet** [comment]
Oh! awesome! Tnx for the info.

**Comment by thet** [comment]
I'll have to look for examples ... In my case I don't want the parent pattern to be applied, just the child patterns. But I think I'll figure it out....

**Comment by jcbrand** [comment]
I don't have any concrete examples for you. This is a relatively obscure feature and I only found out about it because it caused problems for us in one particular instance. However, it's part of the desire to make patterns' configuration similar to CSS.

**Comment by thet** [comment]
ah, ok :)

**Comment by jcbrand** [comment]
I did find this: http://patternslib.com/parameter-syntax/#cascadingconfiguration

Looks roughly similar to what you want to do, right?
