### ISSUE TITLE
Bumper in scroll container

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#436]
I wanted to write a bug report for pat-bumper in the case of scroll containers after I didn't manage to get my bumpers to bump. I've set up an isolated example in this test: https://github.com/Patternslib/bumper-test.

In the bumper example, the strong tags in the left column should stay in place when the user scrolls horizontally within the scroll container.

But just before I wrote this ticket I read this line in the documentation: 

> In addition it is required that the scrolling container is the first positioned parent of the bumper (i.e. its offset parent).

The above is most likely the reason that my bumper doesn't bump as it's not positioned as a directly child of the scroll container in the DOM tree. The behaviour that I always assumed was that bumper would look for the first ancestor with position auto/scroll on it and if there was none, would assume body as the desired scroll container. 

Was there a specific reason we went for this implementation instead? If not, would it be reasonable to let it scan for the first scrolling ancestor instead of only looking at the direct parent?

**Comment by jcbrand** [comment]
@cornae I've updated the pattern, so this should be working now.

However, in your example, I had to add `style="overflow-x: hidden"` to `<tbody>` to make it work.

**Comment by cornae** [comment]
Works well! But why is overflow hidden necessary? Usually you would like it to work with overflow auto. Or would that be fine too?

**Comment by jcbrand** [comment]
I'm not exactly sure anymore, since it's 18 days ago I looked at it. I think it might be specific to tables and how they behave.

**Comment by cornae** [comment]
Yes I know. I couldn't directly reproduce it at that moment because the
example didn't seem to have the updated script, so I needed more time to
build a new time. I had that time yesterday.

I noticed that it doesn't work in Firefox. It might be related to the fact
that it's a table element, but it's strange though, as the tbody is set to
`display: block` which should make it behave just like an ordinary DIV for
instance.

Op do 18 feb. 2016 om 09:11 schreef JC Brand <notifications@github.com>:
