### ISSUE TITLE
bundle download is broken

### ISSUE THREAD

**Issue by petri** [Patternslib/Patterns#438]
Trying to load a bundle from patternslib.com results in error from nginx

**Comment by pilz** [comment]
eii, not good, looking into it right away

**Comment by pilz** [comment]
Should be working again. Seems we had a destrucive security upgrade…

**Comment by petri** [comment]
Ahem, this is still, or again, broken...

**Comment by petri** [comment]
Seems to work now.

**Comment by pilz** [comment]
There was another update with restart, the glibc one, and I hadn't gotten around to debug the root problem. The reboot cronjob was faulty, I fixed that now. I also finally added some monitoring. I'll shut it down now for a short while to test, then this should be a thing of the past.

**Comment by pilz** [comment]
reboot cronjob is fixed and monitoring is in place.
