### ISSUE TITLE
auto-suggest SASS compilation fails

### ISSUE THREAD

**Issue by petri** [Patternslib/Patterns#439]
Upon installing patternslib via bower, SASS via "gem install sass" and then going to patternslib directory and running "make all_css":

> Error: Undefined variable: "$colour-accent".
>         on line 490 of src/pat/auto-suggest/_auto-suggest.scss
>   Use --trace for backtrace.
> make: *** [all_css] Error 65

**Comment by cornae** [comment]
Oops, Will fix that.

**Comment by cornae** [comment]
I could so far not reproduce this error with the following procedure:

1. Create a fresh clone of this repository.
2. Run make all from the root

I tried from master. Did you try another branche perhaps?

**Comment by petri** [comment]
I did not try a git clone, but a bower install. It seems to install 2.0.12 by default, ie. if I do "bower install patternslib", that's what I get.

**Comment by petri** [comment]
I tried a git clone for 2.0.12 and that fails the same way. Master clone seems to not raise the same error, so I guess this has been fixed since.

**Comment by jcbrand** [comment]
I think it's time for a new release, will do so in the coming days.
