### ISSUE TITLE
Style Guideline: define quote marks

### ISSUE THREAD

**Issue by thet** [Patternslib/Patterns#449]
The styleguide doesn't mention which quote marks to use and it's use is not consistent. It looks like double quotes are used more often than single quotes.
I propose to define it once and for all.
I suppose to use the Google recommendation:

https://google.github.io/styleguide/javascriptguide.xml?showone=Strings#Strings
```For consistency single-quotes (') are preferred to double-quotes ("). This is helpful when creating strings that include HTML:```

For the same reason, the Plone styleguide recomends single quotes over double quotes for Python files: http://docs.plone.org/develop/styleguide/python.html#quoting

The jscs tool can help to automate changing the quotes used in Patternslib.

**Comment by jcbrand** [comment]
Originally Wichert enforced double-quotes via JSHint and it was really irritating. I prefer single-quotes, but because it was so irritating to have a certain quote style enforced, I'd prefer to just let people use what they want (as long as it's consistent within code-blocks and structures). I don't really see the point in being strict about something as trivial as this.

**Comment by thet** [comment]
i wouldn't care either, if I the current configuration of jscs and it's integration in vim wouldn't paint me a lot of error marks along the source code and also slow down the editor.
I could change the jscs setting to only check for consistency, but the files aren't all consistent in their use of quotation marks.
also, I like to not having to think about what quote style I prefer more at time of writing.

Whatever, I'm also fine with changing my settings to check for consistency and do a cleanup PR for that, at some point.

**Comment by jcbrand** [comment]
>  I like to not having to think about what quote style I prefer more at time of writing.

I don't think about it, I just type what comes naturally ;)

To now enforce a certain quote-style will mean that half of the code is "wrong", regardless of which style is enforced. I'd prefer it if you fixed your errors by configuring jscs.

**Comment by jcbrand** [comment]
However, if more people felt very strongly about it, or if you wanted to clean up the whole codebase to make it consistent, then I'm not going to stand in your way.

**Comment by thet** [comment]
I agree, updating my config is better than refactoring everything to match a specific quote style :D
