### ISSUE TITLE
[patternslib.com] Plone Intranet Prototype link is broken

### ISSUE THREAD

**Issue by acsr** [Patternslib/Patterns#451]
on http://patternslib.com/documentation.html in column "Examples" the link to:
...
The Plone Intranet Prototype
http://prototype.ploneintranet.net/dashboard.html
...

is broken.

Linking a Quaive resource would be nice. But should be maintained using a redirection intermediate link, that can be pointing to the latest demo or an instance of the old Plone Intranet Prototype for reference.

**Comment by pilz** [comment]
Yes, we did that a while ago, I wasn't aware of this ticket. Thanks for the ping.
