### ISSUE TITLE
pat-scroll offset calculation is erratic on re-entrant scrolling

### ISSUE THREAD

**Issue by gyst** [Patternslib/Patterns#453]
Pat-scroll is triggered correctly on pat-inject updates. But on a long page where part of the content is not visible because of overflow, the scrolling offset is then calculated wrongly. This manifests in two ways:

1. On repeated (autoload-delayed) injection, the page starts to see-saw: it scrolls up on injection, scrolls down on the next injection. See screenshot below with the offset calculation inspected.

2. More subtly, when injecting new content that changes the page length, this extra length is not taken into account (so the extra content remains 'below the fold' in the overflow area), even when waiting for a full scroll-up, scroll-down cycle as described in (1) to complete.

Both appear to be effects of wrong assumptions in calculating the offset. I've been staring at the offset calculation but unable to find the cause for this.

![pat-scroll](https://cloud.githubusercontent.com/assets/122351/17665623/6b5db242-62fc-11e6-9335-6af4ff9037e4.png)

**Edit** an even simpler reproduction: loading a long page directly with a fragment url pointing to the scroll target (``site/foo#target``), will incorrectly scroll only part of the page. Maybe that helps.

**Comment by pysailor** [comment]
Although there's no description present, #446 also dealt with a see-sawing effect with scrolling on repeated injection. Potentially related.

**Comment by gyst** [comment]
Yes I've looked at that change but don't think that is the cause, nor the fix.

Relevant to note is, that in the scenario I'm describing the scroll target is part of a separate scrollable with overflow, inside the page.

**Comment by gyst** [comment]
I've checked in a branch https://github.com/Patternslib/Patterns/tree/453_scroll_calculation that changes the scroll `index.html` page in a way that highlights multiple problems:

- `pat-scroll` links outside of the scrollable don't work

- `pat-scroll` link to `#bottom` at bottom demonstrates wrong offset calculation

**Comment by cornae** [comment]
@pilz, Since you did the updates to pat-scroll, could you maybe have a look at it? It's the same calculation problems that I saw back then and you seemed to be close to a solution.

**Comment by gyst** [comment]
PR with fix is in #455.
