### ISSUE TITLE
Timezone Picker as a distinct pattern

### ISSUE THREAD

**Issue by janga1997** [Patternslib/Patterns#454]
As an addition to colour-picker and date-picker, I was thinking about a Timezone Picker as a distinct widget, using the moment-timezone.js library.
 A demo as to how it will look like can be seen [here](http://momentjs.com/timezone/).
![timezone](https://cloud.githubusercontent.com/assets/15131207/17737043/99942ee0-64a8-11e6-95ed-16408b42d21e.png)

**Comment by jcbrand** [comment]
I see moment-timezone is already loaded in the date-picker pattern. Wouldn't it make sense to extend that pattern to also allow choosing a timezone (either on its own, or as part of a date), then to create a separate pattern for it?

**Comment by janga1997** [comment]
@jcbrand That does seem a better idea. 
Could you clarify what you meant by "either on its own, or as part of a date" ?

**Comment by jcbrand** [comment]
> Could you clarify what you meant by "either on its own, or as part of a date" ?

I mean that there are two usecases for choosing a timezone. Either you want to choose a timezone together with a date, or you want to choose only a timezone without an accompanying date. In both cases pat-date-picker could be used.

Perhaps @cornae would like to chime in as well.

**Comment by janga1997** [comment]
For the use case where we want to choose a timezone with a date,  I agree with you, it would be enough to extend the date picker pattern to include timezones.
But for the use case where we want to choose only a timezone, wouldn't a separate pattern make sense, with a graphical interface  like the demo I linked above?
