### ISSUE TITLE
Publish Patternslib as NPM package?

### ISSUE THREAD

**Issue by jensens** [Patternslib/Patterns#483]
I think it is a good idea to publish patternslib on https://www.npmjs.com 

Is there any reason to not do so?

**Comment by jcbrand** [comment]
Not that I'm aware of. +1

**Comment by pigeonflight** [comment]
+1 patternslib on npm would be more "javascriptic" (if there's such a word).

**Comment by pilz** [comment]
I am working on a few bugfixes at the moment. I will publish it on npmjs with the next release.

**Comment by jcbrand** [comment]
@pilz It would be a good idea to create an NPM Org for Patternslib, so that multiple people can make releases.

More info here: https://www.npmjs.com/docs/orgs/

**Comment by pilz** [comment]
@jcbrand I tried that and have a scope named patternslib now. https://www.npmjs.com/package/@patternslib/patternslib
I added you.

**Comment by pilz** [comment]
It is now possible to install patternslib using npm install @patternslib/patternslib
