### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by janga1997** [Patternslib/Patterns#493]
This seems to be a recurring error when installing

```
node_modules/.bin/r.js -o build.js

Tracing dependencies for: almond
Error: ENOENT, no such file or directory '/home/janga/Patterns/src/bower_components/AnythingSlider/js/jquery.anythingslider.js'
In module tree:
    patterns
      pat-carousel

Error: Error: ENOENT, no such file or directory '/home/janga/Patterns/src/bower_components/AnythingSlider/js/jquery.anythingslider.js'
In module tree:
    patterns
      pat-carousel

    at Object.fs.openSync (fs.js:439:18)

make: *** [bundle.js] Error 1
```
I've made sure that the node and npm version is the same as the that in the latest TravisCI tests.

I understand that there is no `js/` directory in `AnythingSlider`, but I don't know what to do about it.

**Comment by pilz** [comment]
Yes, this is the error when a file is referenced but not present. I just tried to build latest master and that went fine and I also get a js dir in Anythingslider. That makes me assume that something went wrong with your bower download. I see that quite often. Try a make clean and rebuild.

Let me know if that worked.

**Comment by janga1997** [comment]
Yeah, I fixed it.
I manually installed AnythingSlider, and bumped up the version to 1.9.6 , rather than 1.8.17 (required by patternslib), and it worked.

**Comment by janga1997** [comment]
@pilz While you are here, could you help out with #320 ? 
I have been trying to get started on Patternslib for a while now, and I figured writing demos and tests may be a good way.
