### ISSUE TITLE
"Make" is broken

### ISSUE THREAD

**Issue by pysailor** [Patternslib/Patterns#507]
Running `make` gives me
`node_modules/.bin/r.js -o build.js

Tracing dependencies for: almond
Error: ENOENT: no such file or directory, open '/home/thomas/dev/Patterns/src/bower_components/ev-emitter/ev-emitter/ev-emitter.js'
In module tree:
    patterns
      pat-equaliser
        imagesloaded

Error: Error: ENOENT: no such file or directory, open '/home/thomas/dev/Patterns/src/bower_components/ev-emitter/ev-emitter/ev-emitter.js'
In module tree:
    patterns
      pat-equaliser
        imagesloaded

    at Error (native)

Makefile:65: recipe for target 'bundle.js' failed
make: *** [bundle.js] Error 1
`

**Comment by jcbrand** [comment]
Could be that `ev-emitter` is not pinned and that a newer version has been pulled in that has a different directory structure, so require.js can't find it anymore.

**Comment by pilz** [comment]
Fixed that.
