### ISSUE TITLE
pat-validation fails partially on "greater than zero"

### ISSUE THREAD

**Issue by pysailor** [Patternslib/Patterns#508]
I have a form with an input  `type="number" min="0" required="required"`. While I correctly see an error for values less than 0, I do not get a validation error if the value is not a number or the field is empty. In the example given in the pattern (min="16") on the Patternslib website, the validation works for all cases (number, required). If I change min="0" to a positive number, my validation also works.

I want to achieve: validation that the user inputs a positive number.

(I would have made a failing example in a branch, but #507 prevents me from creating it.)

**Comment by cornae** [comment]
I understand the problem. Would one of the following things help? (just some ideas)

- Update the underlying validation polyfill to a newer version.
- Try without pat-validation and with native validation instead (selected browsers) (I'm intrigued if this is an issue of the .js framework or a choice within the HTML standard).
- Try with value min="1" or a the lowest positive decimal value within the constraints of the size value.

**Comment by pysailor** [comment]
Thanks for your suggestions:
1. Is probably worth a try
2. But if the form uses pat-validate for other use cases, wouldn't we have a mixture of (nicely formatted) pat validation errors and native browser errors?
3. Yes, min="1" certainly works, but is semantically not correct. The user in this case is allowed to input any positive number or zero.

**Comment by cornae** [comment]
2. We would and that's not desirable, but it seemed this easiest way to me just to find out how the native standard solves this part.

**Comment by pilz** [comment]
I am trying the update validation path as part of my current upgrade to webpack.

**Comment by pilz** [comment]
In branch deprecate-bower, validate.js is bumped to 0.11.1, the newest version. Is there a place in proto where I can test this?

**Comment by pysailor** [comment]
@pilz If you change this line
https://github.com/Patternslib/Patterns/blob/master/src/pat/validation/index.html#L15
to use `min="0"` you will have a test case.

**Comment by pilz** [comment]
Ok, by setting min="0" and typing "foo" I don't get an error either with 0.11.1.

**Comment by pilz** [comment]
I debugged it and it turns out that input.value is always 0 if the value input can't be parsed. The field is type="number" so "foo" can't be parsed and the browser returns "" which javascript turns into a 0. 
I am not even able to retrieve the originally typed text as long as the type is "number". 
Unfortunately this means that this could only be tackled by turning the field into a string field and performing the validation manually via validate js code. Alternatively you could require the value to be at least 1, that way you get an error for everything not being a natural number.

**Comment by pysailor** [comment]
Ok, I see, thanks.
The use case was a required field where the user needs to enter a number that can be zero or greater. If the field were not required, I could use the work-around of "at least one".
So I'll go for the manual validation.

**Comment by pilz** [comment]
In a review we found that the issue is the required attribute which is in the patterns example but not in Euphorie. Without the required, the behaviour is as expected.
