### ISSUE TITLE
Consolidate pat-select

### ISSUE THREAD

**Issue by pysailor** [Patternslib/Patterns#512]
Problem:
pat-select lives in https://github.com/Patternslib/Patterns/blob/master/src/pat/selectbox/selectbox.js
It defines as trigger "select".
However, the selector used is ".pat-selectbox" (line 37, 39, 43)

This has lead to various issues over the past 2 years, most recently quaive/ploneintranet.prototype#519

So, although the `data-option-value` had been added in f81799a, it is not present in our markup, since we use "pat-select".

Therefore, as a minimal solution, update this pattern to also use ".pat-select" as selector.

Ideally, also the code that adds the param `data-option` should be moved out from checked-flag to here, so that the code for both params (both are needed!) is together:
https://github.com/Patternslib/Patterns/blob/master/src/pat/checked-flag/checked-flag.js#L185

**Comment by pysailor** [comment]
@pilz, did you get a chance to look at this yet? It would be a great addition to the recent reworking of Patterns....

**Comment by pilz** [comment]
It's on the list… :)
