### ISSUE TITLE
pat-date-picker not in ISO8601 format due to moment.js

### ISSUE THREAD

**Issue by thet** [Patternslib/Patterns#519]
pat-date-picker sets the value of the input fields to a human readable format - something like

``2017-09-15`` becomes ``Fri Sep 15 2017``.

This is not so helpful when transmitting to the server, because it must be parsed from an probably localized and unknown format to a ISO 8601 representation or whatever the date library on the server understands.

I would either make the moment.js parsing optional or let ``pat-date-picker`` create a new input field and hide the original one and update the original one with a ISO8601 formatted value when the value is changed in the datepicker-input field.

How are you handling this? /cc @pilz @pysailor @ale-rt

**Comment by pilz** [comment]
Good question. I think we don't have the issue as we are displaying dates mostly in an ISO format. Here is a tag in actual use in the case-manager of PI:
<input placeholder="JJJJ-MM-TT" class="pat-date-picker focus" type="text" size="8" name="earliest_created" data-pat-date-picker="behaviour: polyfill; show: date; i18n: https://ikath.zhkath.ch/@@date-picker-i18n.json">

Does that help?

**Comment by thet** [comment]
tnx for the answer - yes this info does help.

It looks like as if setting the min and max values via moment is responsible for changing the value, which is set in iso format to the longer format:

https://github.com/Patternslib/Patterns/blob/master/src/pat/date-picker/date-picker.js#L40

```
"minDate": this.$el.attr("min") ? moment(this.$el.attr("min")).toDate() : undefined,
"maxDate": this.$el.attr("max") ? moment(this.$el.attr("max")).toDate() : undefined,
```

I'll investigate further and provide evetual fixes in this WIP PR: https://github.com/Patternslib/Patterns/pull/520

I'll prepare a PR for a datetime picker, there will probably also some fixes

**Comment by thet** [comment]
Not an issue anymore. Was fixed along the way.
