### ISSUE TITLE
Wishlist: Upgrade to jQuery 3

### ISSUE THREAD

**Issue by pilz** [Patternslib/Patterns#532]
When looking into https://github.com/quaive/ploneintranet.prototype/issues/547, I had to downgrade jquery to get masonry to work again in ie11. The alternative would've been to upgrade to jquery 3, which seems a bit much for a bugfix.

However mid term this should be the goal.

- Here is the upgrade guide: https://jquery.com/upgrade-guide/3.0/
- The blog post: https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/
- And a migrate script which can make old code work while dumping log messages so that you can gradually upgrade: https://www.npmjs.com/package/jquery-migrate

**Comment by wichert** [comment]
Right now jQuery 1.11 already broke patternslib (see #536 )

More generally: is there any reason to still use jQuery? With modern browsers there really isn't that much need for it anymore in my experience (I haven't used it in a few years now).

**Comment by pilz** [comment]
Basically this is about the amount of resources required to rewrite and assure that it still works. We don't have high test coverage…

**Comment by pilz** [comment]
(but I am all for it!)

**Comment by fulv** [comment]
According to https://jquery.com/upgrade-guide/3.0/, here are the browsers supported as of 3.0:

- Internet Explorer: 9+
- Chrome, Edge, Firefox, Safari: Current and Current - 1
- Opera: Current
- Safari Mobile iOS: 7+
- Android 4.0+

Just so there aren't any surprises.

**Comment by pilz** [comment]
This is no longer a wishlist item, it is reality. We have green tests for the jquery-migrate branch. 

I propose the following approach to merge:

1. Update the Changelog and make a prominent note of the following changes.
2. create a 3.0 branch for the current status quo
3. Make sure the patterns website utilizes the 3.0 branch until further notice
4. Update the version number to 4
5. Merge the jquery-migrate branch to master
6. Communicate and invite testers

**Comment by pilz** [comment]
done
