### ISSUE TITLE
This site can’t be reached when visiting http://patternslib.com/

### ISSUE THREAD

**Issue by pigeonflight** [Patternslib/Patterns#565]
When I attempt to visit http://patternslib.com/ using Chrome. I get

    This site can’t be reached

![screenshot 2017-12-31 at 12 42 45](https://user-images.githubusercontent.com/31827/34463382-22cb193a-ee28-11e7-85d9-69238106f42f.png)

**Comment by pilz** [comment]
Fixed :)
