### ISSUE TITLE
Review pat-tooltip positioning algorithm

### ISSUE THREAD

**Issue by pilz** [Patternslib/Patterns#586]
When a tooltip opens and there is not enough space below or above, it should choose the middle position. Currently it doesn't do that. Fix it.

Also when in progress, it adds the tag <progress/>. To be consistent with other patterns, this should be a class "injecting" instead.

**Comment by pilz** [comment]
Next steps:
- Await completion of new tooltip styling in oira
- Add the new tooltip pattern to quaive proto
- Reassess problem with new pattern.

**Comment by cornae** [comment]
This ticket is no longer relevant.
