### ISSUE TITLE
Enhance autosuggest for single-select

### ISSUE THREAD

**Issue by pysailor** [Patternslib/Patterns#598]
Currently, the support for single select is poor in pat-autosuggest. While it is possible on a technical level via `max-selection-size` to limit the number of values to 1, the display of a single-select selector does not differ from the default multi-select (using pills).

select2 however does offer proper support for the single select case. We should extend pat-autosuggest to support this. Probably, we also need to update the version of select2 being used.

@cornae Please update this description by what you know, then please assign to @pilz so that he can investigate this.

**Comment by pilz** [comment]
Fact gathering:
- Cornelis checks if we have markup changes to expect
- Alex checks if we must upgrade jquery to upgrade select2

**Comment by pysailor** [comment]
@cornae If I understand correctly, you have already done some research regarding the markup. What are your findings?

**Comment by cornae** [comment]
They changed everything. So it will be some work. On the positive side: there's now a SASS file available.

**Comment by pilz** [comment]
Grooming question: Isn't that done? I saw it integrated into the oira Prototype last week

**Comment by cornae** [comment]
I did it on the OiRA Prototype. But this ticket lives in the Patterns tracker so it has to be done/checked generically too still.

**Comment by pilz** [comment]
@cornae Any idea what we need to check? :)

**Comment by cornae** [comment]
Only if it looks fine after I styled it. I believe we've put the styling of the single select option within the patterns library on hold until we had jQuery 3 which we wanted before switching to the new select2 library, which in turn has markup differences with the older select2 that we use.

**Comment by pilz** [comment]
This ticket needs a decision to switch Patterns and all projects to select2 V4 and then styling needs to switch. This needs to happen in a concerted effort and should planned properly.

**Comment by pilz** [comment]
> select2 however does offer proper support for the single select case. We should extend pat-autosuggest to support this. Probably, we also need to update the version of select2 being used.

select2 does offer proper support. pat-autosuggest now also offers proper support. We don't needed to update the version of select2.

**Comment by pilz** [comment]
data-pat-autosuggest="minimum-input-length: 0" is a quick workaround

**Comment by pilz** [comment]
The reason is: The moment there is a minimum-input-length >0 specified, select2 assumes that you only want to search and not start with all results displayed.
