### ISSUE TITLE
pat-scroll anomaly

### ISSUE THREAD

**Issue by pilz** [Patternslib/Patterns#618]
At the bottom of http://patternslib.com/scroll it says there’s a property offset and there’s a property selector. The question about offset is: Does it really exist? I can’t get it to work. And about selector it says “A selector for the element which will be scrolled. By default it will be the element on which the pattern is declared.” I would expect that it would read ‘the element which will be scrolled TOWARDS’, or does it support both?

What I expect: it scrolls to the position of the selected element and adds the offset value. That was the intention of offset.

But we should get it all matching because each time I touch pat-scroll in quaive or oira there’s noise
Is the offset deducted from the calculated scroll distance?
Offset is used to have an offset of x pixels from the edge of the viewport
So that you don’t scroll tightly to a header for instance, but also leave some space above the header
To make things easier to read or to have space for a fixed element such as a menu
If it does something different then I’m curious what it is and I’ll update the docu accordingly
And then we can introduce a property ‘top/bottom/right/left’ for that other usecase

Whatever offset I define, it results in the pat scroll element becoming unresponsive
I tried data-pat-scroll="offset: 100px" and data-pat-scroll="offset: 100"
The demo page works for the rest well
It’s just that offset doesn’t do anything

**Comment by pilz** [comment]
I have pushed a fix in #622. Can you check if it now works for you?

**Comment by pilz** [comment]
good catch!

**Comment by pilz** [comment]
once done, put the label "review" and put it on @cornae's name so that he can check if that solves his issue.

**Comment by fulv** [comment]
To address my comment about the bouncing up and down, it is due to #627, because if a container has `data-pat-scroll="trigger: auto"` then any of its `pat-scroll` children will also inherit the auto trigger, so everything will try to auto-scroll at the same time.

**Comment by fulv** [comment]
(unless all the children have `trigger: click`)
