### ISSUE TITLE
patternslib.com not available on https

### ISSUE THREAD

**Issue by spereverde** [Patternslib/Patterns#632]
This makes the browsers mark this as an unsecure site...
not urgent yet, but someone who works on the hosting for this might have a quick fix...

**Comment by pilz** [comment]
To fix this, we must change the patternslib.com DNS entry to new servers. 
Github has made changes: https://help.github.com/en/articles/troubleshooting-custom-domains#https-errors

Please let the patternslib.com A record point to ONE of the following IP Addresses
- 185.199.108.153
- 185.199.109.153
- 185.199.110.153
- 185.199.111.153

Then ping me to complete the switch.

**Comment by pilz** [comment]
patternslib.com is now running https!
