### ISSUE TITLE
pat-inject encoding type

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#679]
When using pat-inject, the encoding type of a form is always ‘multipart/form-data type’, also when  the enctype attribute on the form says ‘application/x-www-form-urlencoded’. 

Certain CMS installations accept only one type.

Wish: Let pat-inject respect the enctype that is set on the form.

**Comment by pilz** [comment]
More info on problems with IE11:

It’s hard to nail it. But a form with multiple fields and pat inject on it and auto submit and method is post in lower case. Then the form fields are not passed through to the backend.

**Comment by pilz** [comment]
I checked the code and the encoding type is form-data only if the method is set to POST. 
If the method is set to GET, the encoding should be nothing or x-www-form-urlencoded. 

It is invalid to specify x-www-form-urlencoded and method=POST. 

Could you recheck the markup of the form that gives you the problem? Perhaps paste the form tag here?
