### ISSUE TITLE
pat-autofocus to honor visibility

### ISSUE THREAD

**Issue by pilz** [Patternslib/Patterns#686]
pat-autofocus should only set the focus if the target element is actually visible.

pat-autofocus should always listen to pat-update and if it happens, check if it has become visible and then set the focus.

**Comment by cornae** [comment]
This is about pat-autofocus right or is it specifically about pat-autosuggest to also respect autofocus?

**Comment by pilz** [comment]
autofocus it is :)

**Comment by cornae** [comment]
Ok perfect. Although auto suggest might be an interesting case too for checking on its autofocus behaviour.

**Comment by pilz** [comment]
The problem can be reproduced by going to http://localhost:4001/index-logged-in-var-third-party.html?dashboard-view=Fremdfirmenkoordination and then clicking the ellipsis behind a tool in the "Fremdfirmenkoordination" portlet, then opening "Stichprobe eintragen". The appearing modal should focus in the first input field.

**Comment by pilz** [comment]
The solution is not to listen to pat.update but instead to patterns-injected. Then focus only on the content that has been injected.
Thanks to @cornae the analyst!

**Comment by pilz** [comment]
Should be fixed in a849a8f0ef8d33ca56b468aeb6ba6512e7d93f43

**Comment by cornae** [comment]
First patterns that come to mind that fiddle with display mode of pattern of possible element that has pat-autofocus on it:

- pat-toggle
- pat-switch
- pat-stacks
- pat-collapsible

**Comment by pilz** [comment]
On the Stichproben Eintragen modal, the first field has autofocus.
If you click on "no", a new field appears and it should get the autofocus because autofocus should be reevaluated on objects that "appear".

**Comment by pilz** [comment]
All four patterns above throw a pat-update event when they trigger. So if autofocus listens for that, it should behave as intended. I pushed a fix to patterns and oira.prototype, please retest.
