### ISSUE TITLE
Pat inject source value empty

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#689]
Sometimes I need to 'destroy' an element by replacing it with nothingness. Adding a further more unless empty element to the markup is dirty. A special value none for the property source would do the trick.

**Comment by pilz** [comment]
Same concern as stated in the sister ticket about the overloaded word "none".
It would help developers to name this more pictoresque, I think. Perhaps "nothing" or just an empty string ('') perhaps?

**Comment by pilz** [comment]
@cornae I need your input here

**Comment by pilz** [comment]
A first attempt is implemented and pushed to patternslib. Please try if it behaves as you like. 
A test is available at the end of the pat-inject demo page.
