### ISSUE TITLE
Cleanup bundle-config.js

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#693]
File includes that I probably don't need to see in the config file:

- pat-input-change-events
- pat-legend (Could become part of or a dependency of pat-form)
- jquery.browser 
- jquery (A dependency for all the patterns)
- pat-checkedflag (Could probably become a part of pat checklist or a dependency thereof)
- pat-depends_parse (dependency for pat-depends?)

I'm not 100% sure what the following includes do. Might be dependencies too.

- pat-menu
- pat-url
- pat-placeholder

**Comment by pilz** [comment]
The goal of this ticket is to 
a) get rid of the src/patterns.js and move it to ./bundle-config.js to achieve consistency over all projects and reduce confusion.
b) Find out whether all the above mentioned packages must be in that bundle-config or whether they are already pulled in as a dependency of other packages. That way we can reduce the config to only include patterns that really are patterns.
