### ISSUE TITLE
Before/after date validation should not trigger on empty dates

### ISSUE THREAD

**Issue by pysailor** [Patternslib/Patterns#711]
Use case:
I have 2 date fields in a form, a start and an end date. `pat-valdiation` is used to make sure that the start date comes before the end date. (The start date validates for "not after end" and the end date validates for "not before start")
The end date is not a required field. The user should be allowed to enter only a start date.

But in such a case, the validation fails for the end date: "This date must be on or after the start date". I think in the case of a "None" date, the before/after validation should not kick in.

This can be reproduced with the given example on the pattern: https://patternslib.com/validation

It seems that an attempt to resolve this has already be done, according to this comment. 
https://github.com/Patternslib/Patterns/blob/master/src/pat/validation/validation.js#L118
But apparently that is not working.

**Comment by thet** [comment]
https://github.com/Patternslib/Patterns/pull/717

**Comment by thet** [comment]
Additional to the request outlined above:
Only validate empty dates if field is required. Currently validation fails when a non-required field does have an empty date.

```
<form class="pat-validation">
  <input type="date" name="date">
</form>
```
vs
```
<form class="pat-validation">
  <input type="date" name="date"  required="required">
</form>
```
