### ISSUE TITLE
Pat depends always sets inline style

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#719]
Pattern depends sets the display property in the style attribute of an element in the default setting. 

When the transition property is set to 'css', no style attributes should be set, because the designer will do this in the CSS. The problem is that pat depends still sets the style attribute, even if the transition property is set to 'css'. 

As a result, the designer will always have to overrule the display method with `!important` in the CSS. 

Probably related to https://github.com/Patternslib/Patterns/pull/718

**Comment by thet** [comment]
I cannot fully reproduce the problem but found the following:

- ``hidden`` and ``visible`` classes are always set to the ``pat-depends`` item.
- When the transition property is set to ``css`` then no style attributes are set.
- In the default behavior or when transition is set to ``none`` a ``style="display: hidden"`` is added.

I think I do like the behavior that pat-depends adds the style attribute when ``transition:none`` as it makes Patternslib useable without any other styles.
On the other hand, we could provide default styles for this case - but need to make sure that they do not conflict with the ``transition:css`` case - maybe by
1) adding another class showing the transition type (e.g. ``pat-depends--transition-none``, ``pat-depends--transition-css`` or the like) and then ``.pat-depends--transition-none.hidden { display: none; }``
or
2) doing only ``.hidden:not(.in-progress) { display: hidden; }`` which would probably also be enough.

@cornae if it doesn't work for you with ``transition: css``, please show me a demo.
@pilz @cornae I need some input.

**Comment by cornae** [comment]
@pilz @thet Shall we setup a call with screen sharing, uses cases, examples, brainstorming, etc for these complex questions today or tomorrow?
