### ISSUE TITLE
Pat scroll selector: top

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#721]
An important use case for pat-scroll is to use it to auto scroll to the top of a content when you come from an overview page at a larger position. Generally the designer wants to scroll to the top most position. In some designs it's hard to find a suitable element to scroll to. A proposed solution is to introduce a special value 'top': `selector: top`. The value 'top' could be used instead of a CSS selector in case no usable element is available in the design.

I've fitted the test page with an example.

**Comment by thet** [comment]
Notes:
- selector: top should scroll to position 0/0
- selector should take precedence over href
- Branch with demo page: https://github.com/Patternslib/Patterns/compare/scroll-selector-top
- Prototype ticket: https://github.com/quaive/ploneintranet.prototype/issues/986
