### ISSUE TITLE
Pat-inject and Error messages

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#735]
Currently, error codes are not picked up by Patterns. By consequence, a user might be looking at an infinitely spinning spinner after clicking on a link when the session is expired. The situation for a 503 and a 401 is similar. 

## Goal

User comes to an understanding why the desired content is not loading.

## Suggested solutions

1. A data attribute is placed on body that can be turned into a visible message for the user (Something similar is currently done with 404s).
2. An automatic redirect URL is assigned for various error messages through an inject property on every relevant link or form. IE `url-401: /401.html`.
3. An automatic redirect URL is assigned for various error messages through meta tags. IE `<meta name="url-404" content="/404.html">`.
4. A (translatable) message in a meta tag that will be displayed (IE by putting the text in a data attribute on body) when an error code is returned. IE `<meta name="url-401" content="You are not authorised to view the requested content.">`.
5. A simple code is placed in a data attribute on body. IE `data-error-code: 401`. This code is translated into a visible error code by the CSS. Every theme can have its own language. 
- …?

**Comment by pilz** [comment]
Good info: If I can't access something and I am already logged in, there is no need to redirect to the login form, because that only benefits the admin. All other users will try to log in again just to get another insufficient privileges.

**Comment by pilz** [comment]
This is a js ticket to change pat-inject in a way that it would replace the whole body tag of the page with the body of the given error page in case an http error code is returned.

**Comment by thet** [comment]
@cornae this feature was implemented in https://github.com/Patternslib/Patterns/pull/788
It is already available in latest ploneintranet.prototype.
There is some documentation on this feature in:
https://github.com/Patternslib/Patterns/blob/master/src/pat/inject/documentation.md#configurable-error-pages
