### ISSUE TITLE
pat-validation broken with radio inputs

### ISSUE THREAD

**Issue by pysailor** [Patternslib/Patterns#744]
Example: Oira Prototype http://proto.oiraosha.syslab.com/profiling.html

We have a form with pat-validation, and a number of radio-inputs, which are required.

When all radio-elements have been filled and the form gets submitted, pat-validation complains about missing input. (Independently which options are chosen)

<img width="1046" alt="Screenshot 2020-08-17 at 15 45 09" src="https://user-images.githubusercontent.com/642660/90403605-85f4f080-e0a1-11ea-96ed-5c9f187768d3.png">

Detail of markup:
<img width="1762" alt="Screenshot 2020-08-17 at 15 50 52" src="https://user-images.githubusercontent.com/642660/90403676-973dfd00-e0a1-11ea-8ddc-bc4d3d49e77e.png">

The error also happens in the ES6 branch (and in dev).

**Comment by thet** [comment]
Fixed with: https://github.com/Patternslib/Patterns/pull/936
