### ISSUE TITLE
ES6: display issue with pat-select

### ISSUE THREAD

**Issue by pysailor** [Patternslib/Patterns#746]
I'm comparing OiRA prototye, in daimler-style: `bundle exec jekyllerve --config=_config.yml,_config-daimler.yml`

On the dashboard (/index-logged-in.html) there's a pat-select. In master, the selected (default) value is displayed correctly:
<img width="1919" alt="Screenshot 2020-08-20 at 17 31 20" src="https://user-images.githubusercontent.com/642660/90793423-03239e00-e30c-11ea-8c76-03dd32b0cf5e.png">

In ES6, I only see the arrow. 
<img width="1919" alt="Screenshot 2020-08-20 at 17 31 22" src="https://user-images.githubusercontent.com/642660/90793587-2fd7b580-e30c-11ea-91ac-c67b59773585.png">

If I click that arrow, I get to see all options. But after selecting a different option, the display again remains empty.

**Comment by thet** [comment]
Thanks for reporting! Closed with latest changes in https://github.com/syslabcom/oira.prototype/pull/229
