### ISSUE TITLE
Pat-tabs available width calculation issues

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#751]
There are currently issues with how pat-tabs calculates the available width for itself. It seems to depend on the moment when it calculates the available width. This can both result in taking up less width that is available, or sometimes claiming more space than there is.

### Example 1 

https://quaive.cornelis.amsterdam/library.html 

Resize the browser window back and forth with a few pixels and watch the tabs grow and shrink and grow again.

### Example 2

https://quaive.cornelis.amsterdam/workspaces/open-market-committee/index

Click on the cog wheel. Sometimes all four tabs will shown, sometimes only 2 or 3, even if there is space for 4. Also it happens that all 4 tabs are shown and the more tabs span is still injected in the markup even if the span is empty. It's difficult to reproduce this. It all seems to depend on race condition. Speed of the line, speed of the browser, etc.

## Ideas

The measuring of the available width would probably need to happen in a certain order:

1. Hide the element that has pat-tabs on it. 
2. Measure the available space. That is the content width (so the inner width) of the parent element of the element that has the class .pat-tabs.
3. Who pat-tabs with a max-width inline style property on it that has the parent's content width as its value.
4. Put a class 'tabs-ready' on the pat-tabs element once everything is done.
5. Repeat when mutations are observed in the DOM.

**Comment by thet** [comment]
Fixed with: https://github.com/Patternslib/Patterns/pull/773
