### ISSUE TITLE
Pat-tabs open more tabs on click

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#752]
Currently the more tabs span of pat-tabs responds to hover and on most touch devices it responds to tap (CSS only). Sometimes a click would be more appropriate on desktops too. This could be achieved by alternating between the classes `open` and `closed` on the pat-tabs element when the user clicks on the span. The rest can then be done with CSS.

**Comment by thet** [comment]
Fixed with: https://github.com/Patternslib/Patterns/pull/773

**Comment by cornae** [comment]
Hi @thet, thanks for this. I noticed that the class went to the span element instead of to the pat-tabs element. I can work with that too, albeit that having the Classon the pat-tabs element would have me given more freedom. Was it not possible according to spec?

**Comment by cornae** [comment]
Second question, I notice that the class for open is 'opened' instead of 'open'. Was there a special reason for that?
