### ISSUE TITLE
pat-autofocus in an iframe context

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#761]
When pat-autofocus is used on a page that runs in an iframe/object context, then most likely it's not desired to apply autofocus as it takes control away from the host page. Ideally, pat-autofocus would detect that it's running in an an iframe/object context and in that case not execute.

**Comment by pilz** [comment]
The reason for this is that if we have a help page with many images, the page starts hopping wildly around, moving fields into view as they appear on loading. Seen on the oira help pages.
