### ISSUE TITLE
pat-scroll broken for Cornelis

### ISSUE THREAD

**Issue by pilz** [Patternslib/Patterns#763]
Rolling back one commit fixes it. Cornelis currently runs on https://github.com/Patternslib/Patterns/tree/scroll-hotfix-3.x

Please get in contact with Cornelis to find out what was lost and reembed the missing functionality into the 3.x branch and into master.

**Comment by thet** [comment]
@pilz I'd need a more detailed description about the problem as well as an example to reproduce the problem. Let's talk tomorrow.
