### ISSUE TITLE
Styling for the improved date picker

### ISSUE THREAD

**Issue by pysailor** [Patternslib/Patterns#818]
Following https://github.com/quaive/ploneintranet.prototype/issues/1205, we have an implementation of this improved pattern. It has not yet been merged to master, since styling (and testing I guess) is required.

In Patterns (https://github.com/Patternslib/Patterns/pull/815)
quaive proto (https://github.com/quaive/ploneintranet.prototype/pull/1241)
and OiRA proto (https://github.com/syslabcom/oira.prototype/pull/246) 
we each have a branch in which the new pattern can be tested and styled.

Maybe a joint session would be most efficient, during which I help you get the branches sorted?

**Comment by cornae** [comment]
![image.png](https://images.zenhubusercontent.com/5c929a167a7e856312dbda32/30dd4b37-2af5-4fd1-868b-da911c5f952e)

![image.png](https://images.zenhubusercontent.com/5c929a167a7e856312dbda32/31575636-4034-485c-a9ec-2dee2a7d2cd0)

I made some progress with the styling of the date picker fields in OiRA and in Patternslib, but in OiRA ate least (didn't check Patternslib repo yet) I get double output fields. Only the first one functions. Any idea what causes this?

**Comment by pysailor** [comment]
Interesting…
Indeed - on the "Select standard measures" measures, all seems normal (one output field).
But on the "Add extra measures" measures, the outputs are doubled. My working therory is that this might have to do with pat-clone.
I'm investigating.

**Comment by cornae** [comment]
I've added styling for for a cancel button for the date picker.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/738601/112654053-4cfad680-8e4f-11eb-8161-2d29f0aef57b.png">

I propose the following business rules.

1. Cancel button injected by the pat-date-picker pattern. It goes as `<span class="cancel-button" />` into time.ouput-field element as it's last child. 
2. The cancel button is only present when input field has a value unless the input field is set as required.
3. Clicking on the cancel button will empty the input field from its value. So it's not a reset, it's a clear.

**Comment by pysailor** [comment]
Thanks! 
Just to avoid misunderstanding about rule Nr. 2:
“The cancel button is only present when input field has a value unless the input field is set as required.”
Means: a) The cancel button is only present when input field has a value.  AND b) The cancel button is only present when input field is not required.
correct?

This should be enough for Hannes and me to provide the dev-part of the cancel button. And to figure out why we have the double `<time>` outputs (suspicsion: pat-clone).

**Comment by cornae** [comment]
Yes. Or in other words, the cancel button is visible IF input field has value AND input is NOT required. Or in reverse: There is no cancel button IF input has no value OR input is required.

**Comment by thet** [comment]
I'm working on it and halfway through.
@cornae shouldn't we have a ``<button type="button" class="cancel-button" />`` for proper UI semantics here?

**Comment by cornae** [comment]
It is better. However for Quaive @pysailor and I still need to do an exercise of adding pat-button classes here and there and removing the generic button styling. So I’ll put some more exceptions in the code for now so that we van use a button tag. 

But… for semantic purposes it’s only going to be useful if there’s text in the button. And then we need a translation library too. Whereas users with disabilities can still while the hidden input field ‘by hand’ if they can also fill it. So maybe something more for the future?

**Comment by thet** [comment]
Sure, if this opens up more work and uncertainties that's for the future.
