### ISSUE TITLE
pat-validation fails for email with non-ASCII characters

### ISSUE THREAD

**Issue by thet** [Patternslib/Patterns#819]
pat-validation incorrectly shows an error with a email address with umlauts and other non-ascii characters. Try in demo when started locally started at: http://localhost:3001/src/pat/validation/index.html

Test passes:
```test@ing.at```

Test fails:
```
täst@ing.at
test@iñg.at
```

**Comment by pilz** [comment]
The smtp standard (https://tools.ietf.org/html/rfc821) states for the local part "Any one of the 128 ASCII characters (no exceptions)". So unless we can guarantee somehow that the path from sender to recipient is equipped with only mailservers that implement SMTPUTF8 (which we can't), it seems sensible to me that pat-validation rejects such emails. Am I wrong?

**Comment by cornae** [comment]
I suppose that’s at the risk of the person who owns and enter the e-mail address. SMTPUTF8 exists, so these e-mail addresses exist, so it should be possible to enter them.

**Comment by pilz** [comment]
At this moment, I do not agree because email problems always fall back on the operator of the server, but I will not block this ticket to live here. I would just not implement it at this time.

**Comment by thet** [comment]
Ref:
https://en.wikipedia.org/wiki/Email_address#Internationalization
https://tools.ietf.org/html/rfc6530#section-4.2

**Comment by cornae** [comment]
I would also not implement it with priority either, because these addresses are extremely rare still and we can deliver more value to a wider group of users with other open tickets. 

But as a principle, we should eventually support it. If the mail  server doesn’t support the UTF addresses, then the mail will be bounced. The blame will then go to the party that needs to be blamed, which is the mail server and not the form.

**Comment by thet** [comment]
Since https://github.com/Patternslib/Patterns/pull/936 we're using Web API / browser built-in validation.

Umlauts in the domain and TLD part are accepted:
```
test@iñg.ät
```
Umlauts in the name part are not accepted:
```
täst@ing.at
```

**Comment by thet** [comment]
Closed with: https://github.com/Patternslib/Patterns/pull/936
