### ISSUE TITLE
Packaging Patternslib

### ISSUE THREAD

**Issue by thet** [Patternslib/Patterns#821]
## Rationale

For the upcoming patternslib.com website we want a downloadable version of Patternslib.
The integration of the Patternslib JavaScript/CSS should also be as easy as possible.

## Proposal

1) Patternslib/Webpack needs to know the location of the chunk directory to dynamically load chunks.
   Currently we configure the directory via the global ``window.__patternslib_public_path__`` which points to the location of the Patternslib folder where the ``chunks`` folder is located and needs to be set BEFORE the Patternslib JavaScript is loaded.

   We want to have automatic discovery of the chunks folder by getting the last loaded script via:
   ```
    const scripts = document.getElementsByTagName("script");
    const script = scripts[scripts.length - 1]
    const src = script.src;
   ```
   See: https://stackoverflow.com/a/2976714/1337474

   or (all but IE):
   ```
   const src = document.currentScript.src;
   ```
   See: https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript

   Remove the file part and done.

2) Include necessary styles:

- Style inclusion of necessary CSS/SCSS files from ``node_modules`` and https://github.com/Patternslib/patterns-sass
  via JavaScript imports and some Webpack loaders, as shown in the mockup-updates branch:
  https://github.com/Patternslib/Patterns/tree/mockup-updates
  This dynamic loading can be set on/off via the global variable ``window.__patternslib_import_styles`` and easily set off in environments where this is not useful.

- Or build and bundle patterns-sass as part of the patterns release process.

3) Introduce a deployment process for Patternslib releases:

- Ensure entries in ``CHANGES.md`` for each PR.
- Increase Release date in ``CHANGES.md``.
- Increase release version number for ``package.json`` and ``CHANGES.md``.
- Upload to npm.
- Create a Zip file for patternslib.com.
- Upload Zip release to github.com packages.
- Make sure, patternslib.com includes latest release info.

4) Update patternslib.com technical documentation

- Integration of Patterns in own project.
- Including polyfills for IE11 compatibility.
- Starting a new Pattern via https://github.com/Patternslib/pat-PATTERN_TEMPLATE

**Comment by cornae** [comment]
Hi @thet All sounds good. Do I need to do anything for this? Who will be the assignee for this ticket?

**Comment by pilz** [comment]
@thet will be assigned.
