### ISSUE TITLE
pat-date-picker: Support disabled state in styled behavior

### ISSUE THREAD

**Issue by thet** [Patternslib/Patterns#834]
The new styled behavior needs to support the disabled state.

This is an example HTML structure of the new styled behavior:
```
<time class="output-field" datetime="2021-04-09">2021-04-09<span class="cancel-button"></span></time>
<input name="end" class="pat-date-picker" type="hidden" data-pat-date-picker="after: input[name=start]; offset-days: 2;" value="2021-04-09" data-value="2021-04-09">
```

What should happen, when the input is ``disabled``?
Unfortunately we cannot use the ``disabled`` attribute on HTML elements other than form fields.
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled

I suggest:
- Adding a class ``state-disabled`` to the ``time`` element.
- Preventing the date-picker to open when clicking the ``time`` element.
- Preventing any validation checks on the disabled element.
- Do not show the ``cancel-button``.
- Optional, if not too much effort: Listening for any changes on the ``disabled`` state to re-initialize ``pat-date-picker``.

@cornae @pysailor can you think of anything else?
@cornae is the ``state-disabled`` class OK? If yes, I can go on an start implementing it.

Ref: SCR-1065
Ref: https://github.com/Patternslib/Patterns/pull/815

**Comment by cornae** [comment]
I agree with all the proposals. Bear in mind that a state disabled might be toggled by pat-toggle and in the future also by pat-switch.

**Comment by cornae** [comment]
One comment, so far we've used the class 'disabled' instate of 'state-disabled'. With the knowledge of today I say your class name proposal is better, but there's also something to say for predictability of classes for the person who does the styling.

**Comment by thet** [comment]
@cornae I can also go with ``.disabled`` - should I?

**Comment by cornae** [comment]
Yes let’s.

**Comment by thet** [comment]
Fixed by: https://github.com/Patternslib/Patterns/pull/835
