### ISSUE TITLE
Scroll property for collapsible

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#840]
With a property `scroll: ` for pat-collapsible, pat-scroll like behaviour becomes available icm with pat-collapsible. 

Possible values: 
`scroll-selector: self`
`scroll-selector: #some-css-selector`
`scroll-offset: 20px` 

When the collapsible is initialised, the collapsible will scroll to the indicated position.

**Comment by cornae** [comment]
Agreed that @thet will spend max half an hour on `scroll-selector: self` and if it turns out to be complicated then we will only support `scroll-selector: #some-css-selector`.

`scroll-offset` is also a nice to have.

**Comment by thet** [comment]
@cornae the scrolling should happen in the moment the collapsible is opened. we do not wait for any transitions to be finished, right?
also, when the collapsible is closed, no scrolling happens, right?

**Comment by cornae** [comment]
We do not wait for transitions. It should indeed happen as soon as the collapsible opens. It should not happen when the collapsible closes.

**Comment by thet** [comment]
@cornae couple more questions/remarks:

- I implemented the `self` selector in pat-scroll.

- I need to add support for a `offset` in pat-scroll but there is already a `offset` parameter which does a different thing than we need. When defined it scrolls the scroll container defined by `selector` by the number of pixels defined by the offset parameter.
  But I need a `offset` parameter which can be used together with a `selector` parameter to scroll to the selector-target +/- a `offset`.
  Should we name this `offset` differently, e.g. `selection-offset`?
  Or is the already existing `offset` not being used and can be dropped? 

- Just curious about the difference: isn't the functionality defined here almost handled by the implementation of this issue? https://github.com/Patternslib/Patterns/issues/842

**Comment by cornae** [comment]
The already existing offset isn’t used by us. I would propose to replace it.

**Comment by cornae** [comment]
842 is for scrolling towards an element that sits within a closed  collapsible

**Comment by thet** [comment]
Fixed with: https://github.com/Patternslib/Patterns/pull/856
