### ISSUE TITLE
Pat-bumper update

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#846]
Pat-sticky has become irrelevant in its original form since there is less of an emphasis on IE, for which pat-sticky was a polylfill. There's one feature that CSS cannot do for which pat-bumper is often abused, which is a class that gives away that an element is touching or bleeding out of it's first scrollable pattern. Pat-bumper places a class 'bumped' when this happens. Pat-bumper, which is otherwise also obsolete, is in used in these cases with its positioning properties overruled in the CSS with !importants. We might consider to add a property to pat-bumper that allows for applying its inline style attributes only when required. The class 'bumped' will always be placed and is very useful. 

The property that I propose is: 

`positioning: css/inline`

Where 'css' would mean that the JavaScript will not add any inline style attributes and 'inline' would represent the current behaviour.

I would propose to make 'css' the new default.

**Comment by cornae** [comment]
We take a shortcut and drop the positioning behaviour all together and accept the following:

- Cornelis has to regression test whether current instances of pat-bumper still rely on relative positioning (Unlikely that this is the case)
- IE users will have to scroll to reach a toolbar or button bar in some cases as only browsers younger than 7 years support `position: sticky`.

**Comment by thet** [comment]
We now have a semi-working PR for this issue: https://github.com/Patternslib/Patterns/pull/861

- The JavaScript positioning functionality is completly removed - now position:sticky has to be used.

- Currently we need the following sticky position to detect if the element has bumped on a side:
  ```
    .pat-bumper {
        position: sticky;
        top: -0.51em;
        bottom: -0.51em;
        left: -0.51em;
        right: -0.51em;
    }
  ```
The point is to have a slightly negative sticky position. If the element is not 100% in the viewport, it is stuck and we are setting the class on the pat-bumper element.
A visual space between the sticky container and the sticky element would need a padding in the sticky element.
@cornae is this OK for you?

- The ``margin`` option currently does not work. Before it was used to add a margin to the sticky position, which can now be done in CSS (as padding). We would use this option to detect if the sticky element is bumping on the specified side, considering a space between the sticky container and the element.
@cornae is this an importan option for you?

- Currently we have some glitches detecting multiple sticky positions. So if a element is stuck on one side, e.g. top it won't detect sticking on another side, e.g. left until it is unstuck from top.
Detecting sticking on top and then bottom works, as normally the element is unstuck from top before it gets stuck on bottom.
@cornae is this limitation a blocker?

**Comment by thet** [comment]
@cornae i think we have it working now.
you can set the .pat-bumper sticky position to whatever you want - we're reading it from CSS and configuring the IntersectionObserver accordingly.

I think we can remove some of the pattern config options.
@cornae can you have a look and check if they are still valid or needed?

These can be removed IMO
- `margin`: not used anymore. the margin is read from the .pat-bumper's CSS and the intersection observer configured accordingly.
- `side`: the bumping side - when bumped a `bumped-top/right/bottom/left` class is added according to the side config. I think we can just safely always add a class according to any bumped side.

These are still used:
- `selector`: the element where the bumping classes are set to. if not given it's the .pat-bumper element itself.
- `bump-add`: the class to add when the element got bumped. default `bumped`.
- `bump-remove`: the class to remove when the element got bumped.
- `unbump-add`: the class to add when the element got unbumped.
- `unbump-remove`: the class to remove when the element got unbumped. default `bumped`.

**Comment by cornae** [comment]
-`margin`: Agree. Basically `offset` is the new `margin` now.
- `side`: Agree. Don't need any longer.

Happy with keeping the rest of the properties.

**Comment by thet** [comment]
Fixed with: https://github.com/Patternslib/Patterns/pull/861
