### ISSUE TITLE
Pat-tabs calculation

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#848]
Pat-tabs doesn't calculate well which items have to move into the span. For example, when you look at the screen below in mobile size, the tabs bar at the bottom of the screen has space for one tab more than it shows.

https://quaive.cornelis.amsterdam/workspaces/asian-steering-committee/index

**Comment by cornae** [comment]
## Calculation order is probably.

1. The whole thing is drawn .
2. Measures the total width of all tabs combined.
3. Measures the available content/inner width of the parent of the element that has pat-tabs on it.
4. If the value of step 2 exceeds the value of step 3, then the surplus of tabs is wrapped in a span.extra-tabs.
5. class .tabs-wrapped is placed if there's a surplus.
6. Measures the content/inner with of the element that has pat-tabs on it (NOT the parent).
7. Recalculates which items have to move into the span.

## Another way to do it is to move the last item into the span, then measure and if necessary repeat this step.

1. The whole thing is drawn .
2. Measures the total width of all tabs combined.
3. Measures the available content/inner width of the parent of the element that has pat-tabs on it.
4. If the value of step 2 exceeds the value of step 3, then the last the of the tabs is wrapped in a span.extra-tabs.

Repeat step 3 and 4 until 3 is false.

**Comment by thet** [comment]
Fixed via: https://github.com/Patternslib/Patterns/pull/862

**Comment by thet** [comment]
I used method 2 - recursion.
It also takes the extra-tabs item and the whitespace between each tab into account. width + border + padding + margin is not enough - there is also the whitespace. i compare the positions of each tab element, and if the next one has a left-position smaller than the previous, then it's breaking into the next line.
