### ISSUE TITLE
pat-bumper bumped class not appearing

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#870]
- [ ] Click the + on this screen https://quaive.cornelis.amsterdam/workspaces/ . The modal the appears has a button bar with pat-bumper on it. When the viewport is too small for the modal, pat bumper should kick in because then the modal becomes a scroll box. I also tried extra negative values for the bottom property, but that didn’t help.

- [ ] A style attribute with `position: relative` is still placed that I need to overrule in the style sheets everywhere I use bumper with `!important`. We could get rid of that inline style attribute too.

An additional example is the button bar in the OiRA prototype on the screen /ass-private-security-grafton-street in the branch portal-renewal.

**Comment by thet** [comment]
Fixes with: https://github.com/Patternslib/Patterns/pull/861
