### ISSUE TITLE
pat-inject error handling: Enrich the error templates with dynamic content

### ISSUE THREAD

**Issue by thet** [Patternslib/Patterns#896]
When a response to a pat-inject request results in an error we have a fallback mechanism so that the user is presented with a error page like the 404 page:

https://quaive.cornelis.amsterdam/assets/quaive/templates/404.html

The global header includes some dynamic content (user avatar, user menu, etc).

Currently the whole template is injected into the current document's body, so the global header is also from the template.

To fix this, I see two options:

1) We include pat-inject statements in the error template to make an ajax request to get the global header from the server.

PRO:
- the task can be done with just changing the error template.

CONS:
- If the global header creates the error we might end up in an infinite loop trying to retrieve the global header.
- This creates additional load on the server which might need some rest.

2) We add another pat-inject error handling configuration to define which part of the error message should be injected into which part of the current page. 

PRO:
- No additional requests have to be made.

CONS:
- We need yet another config option for the error handling.

**Comment by thet** [comment]
Moved to: https://github.com/quaive/ploneintranet.prototype/issues/1423

**Comment by cornae** [comment]
Hi Johannes, I’m not 100% what this is or why it is already closed. I’ve not been involved. Shall we plan a design call on this?

**Comment by thet** [comment]
Hi @cornae,
I just moved it over to https://github.com/quaive/ploneintranet.prototype/issues/1423 because it better fits there.

**Comment by cornae** [comment]
@pilz, should this go into definition?
