### ISSUE TITLE
Pat-tiptap focus class

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#940]
A class 'tiptap-focus' that appears on the editor toolbar element when tiptap gets focus and that disappears when tiptap looses focus. In other words, whenever the class 'ProseMirrorFocussed' is present on 'div.proseMirror'.

**Comment by cornae** [comment]
With this affordance I can hide and show the editing controls when needed.

**Comment by thet** [comment]
Fixed with: https://github.com/Patternslib/pat-tiptap/commit/1d6302280765d620981b2b1640dd7b48ceffc56e
