### ISSUE TITLE
pat-inject autoload-visible with IntersectionObserver

### ISSUE THREAD

**Issue by thet** [Patternslib/Patterns#955]
We had a problem where items which were visible on the dashboard were not loaded due to pat-inject trigger:autoload-visible not kicking in, even if the items were in the viewport when loading.

They were immediately loaded after scrolling once.

We had a quickfix for this.
But this should be fixed in a way, that ``trigger: autoload-visible`` does the expected thing - loading items when they are in the viewport, even without scrolling. We should think of using the intersection observer for that where we can also define a margin for loading items in advance.

**Comment by cornae** [comment]
Don't worry about the margin. I usually tune that with CSS.

**Comment by thet** [comment]
Work is happening here: https://github.com/Patternslib/Patterns/pull/941
