### ISSUE TITLE
Regression in date validation

### ISSUE THREAD

**Issue by pysailor** [Patternslib/Patterns#970]
Scenario: We have 2 date fields, start and end. Start must be before end, and end must be after start.

```
              <input class="pat-date-picker"
                     id="solution-planning-start"
                     name="measure.planning_start:records"
                     type="date"
                     data-pat-date-picker="output-format: D MMM YYYY; locale: de; week-numbers: show;"
                     data-pat-validation="not-after: #solution-planning-end; "
              />

              <input class="pat-date-picker"
                     id="solution-planning-end"
                     name="measure.planning_end:records"
                     type="date"
                     data-pat-date-picker="output-format: D MMM YYYY; locale: de; week-numbers: show;"
                     data-pat-validation="not-before: #solution-planning-start"
              />
```
In previous versions of pat-validation, if the condition "start must be before end" was not met, both fields were marked is invalid.

![Screenshot 2022-03-04 at 13 06 09](https://user-images.githubusercontent.com/642660/156760859-c987ccb8-8a2e-4b03-a8c1-cb7011e4d74d.png)

It was possible to correct the error in either of the fields. Either by moving start before end, or by moving end after start. The validation error was cleared from both fields (and the form in general).

![Screenshot 2022-03-04 at 13 06 54](https://user-images.githubusercontent.com/642660/156761020-ec332040-3e59-4754-82b0-5d8227ab10c8.png)

With the current bundle, the mutual dependency is lost. The validation error only applies to the field that was last changed (start in this case).
![Screenshot 2022-03-04 at 13 12 46](https://user-images.githubusercontent.com/642660/156761573-543c5a05-08e5-4bdb-a401-002bea23ee0f.png)
Fixing the wrong date in the other field has no effect on the validation error.

![Screenshot 2022-03-04 at 13 12 56](https://user-images.githubusercontent.com/642660/156761640-de9553d4-b4d8-4c62-9bc5-3ef8835ad31c.png)

**Comment by thet** [comment]
Fixed in: https://github.com/Patternslib/Patterns/pull/971
@pysailor please review in https://github.com/euphorie/Euphorie/pull/350

**Comment by pysailor** [comment]
Works fine!
